[build]
publish = "public"
command = "cp -R browserconfig.xml assets images favicon.ico index.html github-btn.html manifest.json public/"

[context.production.environment]
HUGO_VERSION = "0.58.3"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"
